import Foundation

extension HKMetadataKey {

    /**
     Provide a nicer description of a metadata key.
     */
    public var description: String {
        switch self {
        case .activityType: return "Activity Type"
        case .algorithmVersion: return "Algorithm Version"
        case .alpineSlopeGrade: return "Alpine Slope Grade"
        case .appleDeviceCalibrated: return "Apple Device Calibrated"
        case .appleECGAlgorithmVersion: return "Apple ECG Algorithm Version"
        case .audioExposureDuration: return "Audio Exposure Duration"
        case .audioExposureLevel: return "Audio Exposure Level"
        case .averageMETs: return "Average METs"
        case .averageSpeed: return "Average Speed"
        case .barometricPressure: return "Barometric Pressure"
        case .bloodGlucoseMealTime: return "Blood Glucose Meal Time"
        case .bodyTemperatureSensorLocation: return "Body Temperature Sensor Location"
        case .coachedWorkout: return "Coached Workout"
        case .crossTrainerDistance: return "Cross Trainer Distance"
        case .cyclingFunctionalThresholdPowerTestType: return "Cycling Functional Threshold Power Test Type"
        case .dateOfEarliestDataUsedForEstimate: return "Date of Earliest Data Used for Estimate"
        case .deviceManufacturerName: return "Device Manufacturer Name"
        case .deviceName: return "Device Name"
        case .devicePlacementSide: return "Device Placement Side"
        case .deviceSerialNumber: return "Device Serial Number"
        case .digitalSignature: return "Digital Signature"
        case .elevationAscended: return "Ascended Elevation"
        case .externalUUID: return "External UUID"
        case .fitnessMachineDuration: return "Fitness Machine Duration"
        case .fitnessPlusSession: return "Fitness Plus Session"
        case .foodType: return "Food Type"
        case .glassesPrescriptionDescription: return "Glasses Prescription Description"
        case .groupFitness: return "Group Fitness"
        case .headphoneGain: return "Headphone Gain"
        case .heartRateEventThreshold: return "Heart Rate Event Threshold"
        case .heartRateMotionContext: return "Heart Rate Motion Context"
        case .heartRateRecoveryActivityDuration: return "Heart Rate Recovery Activity Duration"
        case .heartRateRecoveryActivityType: return "Heart Rate Recovery Activity Type"
        case .heartRateRecoveryTestType: return "Heart Rate Recovery Test Type"
        case .heartRateRecoveryMaxObservedRecoveryHeartRate: return "Max Observed Recovery Heart Rate"
        case .heartRateSensorLocation: return "Location of Heart Rate Sensor"
        case .indoorBikeDistance: return "Indoor Bike Distance"
        case .indoorWorkout: return "Indoor Workout"
        case .insulinDeliveryReason: return "Insulin Delivery Reason"
        case .keySyncVersion: return "Key Sync Version"
        case .lapLength: return "Lap Length"
        case .lowCardioFitnessEventThreshold: return "Low Cardio Fitness Event Threshold"
        case .maximumLightIntensity: return "Maximum Light Intensity"
        case .maximumSpeed: return "Maximum Speed"
        case .menstrualCycleStart: return "Menstrual Cycle Start"
        case .physicalEffortEstimationType: return "Physical Effort Estimation Type"
        case .quantityClampedToLowerBound: return "Quantity Clamped To Lower Bound"
        case .quantityClampedToUpperBound: return "Quantity Clamped To Upper Bound"
        case .referenceRangeLowerLimit: return "Reference Range Lower Limit"
        case .referenceRangeUpperLimit: return "Reference Range Upper Limit"
        case .sessionEstimate: return "Session Estimate"
        case .sessionId: return "Session ID"
        case .sexualActivityProtectionUsed: return "Protection Used for Sexual Activity"
        case .subIndex: return "Sub-Index"
        case .swimmingLocationType: return "Swimming Location Type"
        case .swimmingStrokeStyle: return "Swimming Stroke Style"
        case .swoflScore: return "SWOFL Score"
        case .syncIdentifier: return "Sync Identifier"
        case .timeZone: return "Timezone"
        case .udiDeviceIdentifier: return "UDI Device Identifier"
        case .udiProductionIdentifier: return "UDI Production Identifier"
        case .userMotionContext: return "User Motion Context"
        case .vO2MaxTestType: return "VO2Max Test Type"
        case .vo2MaxValue: return "VO2 Max Value"
        case .wasTakenInLab: return "Was Taken In Lab"
        case .wasUserEntered: return "Entered by user"
        case .waterSalinity: return "Water Salinity"
        case .weatherHumidity: return "Weather Humidity"
        case .weatherTemperature: return "Weather Temperature"
        case .workoutBrandName: return "Workout Brand Name"
        }
    }
}
